#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# config/routes.yaml
index:
    path: /{_locale}
    controller: App\Controller\DefaultController::index
    requirements:
        _locale: '%app.supported_locales%'
    defaults:
        _locale: fr
    
boutique:
    path: /{_locale}/boutique
    controller: App\Controller\BoutiqueController::index
    requirements:
        _locale: '%app.supported_locales%'
    defaults:
        _locale: fr
    
   
contact:
    path: /{_locale}/contact
    controller: App\Controller\DefaultController::contact
    requirements:
        _locale: '%app.supported_locales%'
    defaults:
        _locale: fr
        
        
rayon:
    path: /{_locale}/rayon/{idCategory}
    controller: App\Controller\BoutiqueController::rayon
    requirements:
        _locale: '%app.supported_locales%'
    defaults:
        _locale: fr
            
    
hello_page:
    path: /hello/{userName}
    controller: App\Controller\DefaultController::hello
    defaults:
        userName: 'Anonyme'
        
        
        
panier:
    path: /{_locale}/panier
    controller: App\Controller\PanierController::index
    requirements:
        _locale: '%app.supported_locales%'
    defaults:
        _locale: fr       
        
panier_ajouter:
    path: /{_locale}/panier/ajouter/{idProduit}
    controller: App\Controller\PanierController::ajouter
    requirements:
        _locale: '%app.supported_locales%'
    defaults:
        _locale: fr
        
        
panier_enlever:
    path: /{_locale}/panier/enlever/{idProduit}/{quantite}
    controller: App\Controller\PanierController::enlever
    requirements:
        _locale: '%app.supported_locales%'
    defaults:
        _locale: fr
        
panier_supprimer:
    path: /{_locale}/panier/supprimer/{idProduit}
    controller: App\Controller\PanierController::supprimer
    requirements:
        _locale: '%app.supported_locales%'
    defaults:
        _locale: fr
        
panier_vider:
    path: /{_locale}/panier/vider
    controller: App\Controller\PanierController::vider
    requirements:
        _locale: '%app.supported_locales%'
    defaults:
        _locale: fr
        
        
connexion:
    path: /{_locale}/connexion
    controller: App\Controller\DefaultController::connexion
    requirements:
        _locale: '%app.supported_locales%'
    defaults:
        _locale: fr
        
        
usager_index:
    path: /{_locale}/accueil
    controller: App\Controller\UsagerController::index
    requirements:
        _locale: '%app.supported_locales%'
    defaults:
        _locale: fr
        
        
usager_new:
    path: /{_locale}/inscription
    controller: App\Controller\UsagerController::new
    requirements:
        _locale: '%app.supported_locales%'
    defaults:
        _locale: fr
    
